on:
  workflow_call:
    inputs:
      CONTROLLER-REPO: 
        required: true
        type: string
      CONTROLLER-REF:
        required: false
        type: string
        default: main
      PROJECT-REPO:
        required: true
        type: string

env:
  DOCKER_REGISTRY_BASE_URL: https://partior.jfrog.io/artifactory
  YAML_CONFIG_IMPORTER: yaml_importer_${{ github.run_id }}_${{ github.run_number }}
  YAML_BRANCH_CONFIG_IMPORTER: yaml_branch_importer_${{ github.run_id }}_${{ github.run_number }}

jobs:
  read-repo:
    runs-on: ubuntu-latest
    outputs:
      BRANCH-NAME: ${{ steps.get-repo.outputs.branch-name }}
      REPO-NAME: ${{ steps.get-repo.outputs.name }}
      DELTA-COMMIT-MSG: ${{ steps.get-repo.outputs.delta-commit-msg }}
      COMMIT-HASH: ${{ steps.get-repo.outputs.commit-hash }}
      PR-NUM: ${{ steps.get-repo.outputs.pr-num }}
      PR-TARGET-BRANCH: ${{ steps.get-repo.outputs.pr-target-branch }}
      SOURCE-BRANCH: ${{ steps.get-repo.outputs.source-branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get repo details
        id: get-repo
        run: |
          branchName="$(echo ${GITHUB_REF_NAME} | cut -d"/" -f1)"
          sourceBranch=${GITHUB_REF_NAME}
          prTargetBranch='NIL'
          isPR=false
          commitMessages='NIL'
          commitHash=${GITHUB_SHA}
          prNum='NIL'
          if [[ ! -z "$GITHUB_HEAD_REF" ]]; then
            echo "[DEBUG] This is a PR. GITHUB_HEAD_REF is $GITHUB_HEAD_REF"
            branchName=$(echo $GITHUB_HEAD_REF | cut -d"/" -f1)
            sourceBranch=${GITHUB_HEAD_REF}
            isPR=true
            prTargetBranch=remotes/origin/${GITHUB_BASE_REF}
            git fetch --all
            echo [DEBUG] git log $prTargetBranch..$commitHash --pretty=format:"%s"
            echo [DEBUG] commitMessages=[$(git log $prTargetBranch..$commitHash --pretty=format:"%s" | sed s/[\`\']//g | tr "\t\r\f\n\'\"" ' ')]
            commitMessages=$(git log $prTargetBranch..$commitHash --pretty=format:"%s" | sed s/[\`\']//g | tr "\t\r\f\n\'\"" ' ' | xargs)
            echo [DEBUG] git log $prTargetBranch..$commitHash --pretty=format:"%an"
            echo [DEBUG] commitAuthor=[$(git log $prTargetBranch..$commitHash --pretty=format:"%an" | tr "\t\r\f\n\'\"" ' ' )]
            commitAuthor=$(git log $prTargetBranch..$commitHash --pretty=format:"%an" | tr "\t\r\f\n\'\"" ' ' | xargs)
            echo [DEBUG] commitHash=[$(git log | grep "Merge.*into" | head -1 )]
            commitHash=$(git log | grep "Merge.*into" | head -1 | xargs | cut -d" " -f2)
            prNum=$(echo $GITHUB_REF_NAME | cut -d"/" -f1)
            echo [DEBUG] lastCommitHash=[$(git log -n 1 --pretty=format:'%H' HEAD~1)]
            lastCommitHash=$(git log -n 1 --pretty=format:'%H' HEAD~1)
            echo [DEBUG] lastCommitMsg=[$(git log -n 1 --pretty=format:'%s' HEAD~1 | tr "\t\r\f\n\'\"" ' ' )]
            lastCommitMsg=$(git log -n 1 --pretty=format:'%s' HEAD~1 | tr "\t\r\f\n\'\"" ' ' | xargs)
            echo [DEBUG] lastCommitAuthor=[$(git log -n 1 --pretty=format:'%an' HEAD~1 | tr "\t\r\f\n\'\"" ' ')]
            lastCommitAuthor=$(git log -n 1 --pretty=format:'%an' HEAD~1 | tr "\t\r\f\n\'\"" ' ' | xargs)
          fi
          echo [DEBUG] commitHash=${commitHash}
          echo [DEBUG] commitMessages=${commitMessages}
          echo [DEBUG] commitAuthor=${commitAuthor}
          echo [DEBUG] lastCommitHash=${lastCommitHash}
          echo [DEBUG] lastCommitMsg=${lastCommitMsg}
          echo [DEBUG] lastCommitAuthor=${lastCommitAuthor}
          echo "source-branch=${sourceBranch}" >> $GITHUB_OUTPUT
          echo "pr-num=${prNum}" >> $GITHUB_OUTPUT
          echo "pr-target-branch=${prTargetBranch}" >> $GITHUB_OUTPUT
          echo "commit-hash=${commitHash}" >> $GITHUB_OUTPUT
          echo "commit-sha=$(echo ${commitHash} | cut -c1-8 )" >> $GITHUB_OUTPUT
          echo "branch-name=${branchName}" >> $GITHUB_OUTPUT
          echo "name=$(echo ${GITHUB_REPOSITORY}  | cut -d"/" -f2)" >> $GITHUB_OUTPUT
          echo "delta-commit-msg=${commitMessages}" >> $GITHUB_OUTPUT


  read-config:
    runs-on: ubuntu-latest
    outputs:
      ARTIFACT-BASE-NAME: ${{ steps.pipeline-config.outputs.artifact-base-name }}
      ENABLE-DEPLOYMENT: ${{ steps.pipeline-branch-config.outputs.deployment_enabled }}
      CI-DEPLOYMENT-VERSION-SOURCE: ${{ steps.pipeline-branch-config.outputs.deployment_version-source-manifest }}
      PREPARE-RELEASE: ${{ steps.pipeline-branch-config.outputs.prepare-release_enabled }}
      SIGN-ARTIFACT:  ${{ steps.sign-artifact.outputs.enabled }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.CONTROLLER-REPO }}
          ref: ${{ inputs.CONTROLLER-REF }}
          token: ${{ secrets.GH_REPO_READER_TOKEN }}

      - name: Get repo details
        id: get-repo
        run: |
          branchName="$(echo ${GITHUB_REF_NAME} | cut -d"/" -f1)"
          if [[ ! -z "$GITHUB_HEAD_REF" ]]; then
            branchName=$(echo $GITHUB_HEAD_REF | cut -d"/" -f1)
          fi 
          echo "branch-name=${branchName}" >> $GITHUB_OUTPUT
          echo "name=$(echo ${GITHUB_REPOSITORY}  | cut -d'/' -f2)" >> $GITHUB_OUTPUT

      - name: Generate HELMFILE CI config importer
        uses: partior-libs/gcs-yaml-importer@partior-stable
        with:
          yaml-file: projects/${{ steps.get-repo.outputs.name }}.yaml
          query-path: .docker.ci
          set-sub-default-keys: .docker.ci-default
          output-file: ${{ env.YAML_CONFIG_IMPORTER }}
          yaml-file-for-default: projects/docker-default.yaml
          query-path-for-default: .docker.ci
          upload: true

      - name: Start import pipeline config
        id: pipeline-config
        run: |
          echo Importing ...${{ env.YAML_CONFIG_IMPORTER }}
          source ./${{ env.YAML_CONFIG_IMPORTER }}

      - name: Generate CI branch config importer
        uses: partior-libs/gcs-yaml-importer@partior-stable
        with:
          yaml-file: projects/${{ steps.get-repo.outputs.name }}.yaml
          query-path: .docker.ci.branches.${{ steps.get-repo.outputs.branch-name }}
          set-sub-default-keys: .docker.ci.branches.default
          output-file: ${{ env.YAML_BRANCH_CONFIG_IMPORTER }}
          yaml-file-for-default: projects/docker-default.yaml
          query-path-for-default: .docker.ci.branches.default
          upload: true

      - name: Start import pipeline branch config
        id: pipeline-branch-config
        run: |
          echo Importing ...${{ env.YAML_BRANCH_CONFIG_IMPORTER }}
          source ./${{ env.YAML_BRANCH_CONFIG_IMPORTER }}

      - name: Get artifact signing flag
        id: sign-artifact
        run: |
          packagerEnabled="${{ steps.pipeline-branch-config.outputs.artifact_packager_enabled }}"
          signingEnabled="${{ steps.pipeline-branch-config.outputs.artifact_packager_signing_enabled }}"
          finalSignFlag=false
          if [[ "$packagerEnabled" == "true" ]] && [[ "$signingEnabled" == "true" ]]; then
            finalSignFlag=true
          fi
          echo [INFO] Signing flag=$finalSignFlag
          echo "enabled=${finalSignFlag}" >> $GITHUB_OUTPUT

  ci-build:
    runs-on: ubuntu-latest
    needs: [ read-repo, read-config ] 
    env:
      BRANCH_NAME: ${{ needs.read-repo.outputs.BRANCH-NAME }}
      ALL_DELTA_COMMIT_MSG: ${{ needs.read-repo.outputs.DELTA-COMMIT-MSG }}
      ARTIFACT_BASE_NAME: ${{ needs.read-config.outputs.ARTIFACT-BASE-NAME }}
      COMMIT_HASH: ${{ needs.read-repo.outputs.COMMIT-HASH }}
      PR_NUMBER: ${{ needs.read-repo.outputs.PR-NUM }}
      PR_TARGET_BRANCH: ${{ needs.read-repo.outputs.PR-TARGET-BRANCH }}
      SOURCE_BRANCH: ${{ needs.read-repo.outputs.SOURCE-BRANCH }}
    outputs:
      ARTIFACT-VERSION: ${{ steps.version-bot.outputs.artifact-version-name }}
      ARTIFACT-NAME: ${{ steps.artifact-info.outputs.name }}
      ARTIFACT_BASE_NAME: ${{ needs.read-config.outputs.ARTIFACT-BASE-NAME }}
      ARTIFACTORY-DOCKER-REPO: ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.YAML_BRANCH_CONFIG_IMPORTER }}

      - name: Start import pipeline branch config
        id: pipeline-branch-config
        run: |
          echo Importing ...${{ env.YAML_BRANCH_CONFIG_IMPORTER }}
          source ./${{ env.YAML_BRANCH_CONFIG_IMPORTER }}

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.YAML_CONFIG_IMPORTER }}

      - name: Start import pipeline CI config
        id: pipeline-ci-config
        run: |
          echo Importing ...${{ env.YAML_CONFIG_IMPORTER }}
          source ./${{ env.YAML_CONFIG_IMPORTER }}

      - name: Update prepend automatically
        if: steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_rules_file_auto_enabled == 'true' && steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_rules_file_enabled == 'true' && steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_enabled == 'true'
        run: |
          sourceFile="${{ steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_rules_file_auto_source-file }}"
          sourceKey="${{ steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_rules_file_auto_key }}"
          buildVersion=$(cat $sourceFile | grep -E "\s$sourceKey=" | cut -d"=" -f2 | xargs)
          prependKey="${{ steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_rules_file_key }}"
          prependVersionFile="${{ steps.pipeline-ci-config.outputs.artifact-auto-versioning_prepend-version_rules_file_target }}"

          echo "[INFO] sourceFile=$sourceFile"
          echo "[INFO] sourceKey=$sourceKey"
          echo "[INFO] buildVersion=$buildVersion"
          echo "[INFO] prependKey=$prependKey"
          echo "[INFO] prependVersionFile=$prependVersionFile"

          echo "$prependKey=$buildVersion" > $prependVersionFile

          echo "[INFO] Updated version config:"
          cat $prependVersionFile

      - name: Start versioning bot
        id: version-bot
        if: steps.pipeline-ci-config.outputs.artifact-auto-versioning_enabled == 'true'
        uses: partior-libs/gcs-versioning-bot@partior-stable
        with:
          jfrog-token: ${{ secrets.JFROG_ARTIFACTORY_CONFIG }}
          versioning-rules-importer-file: ${{ env.YAML_CONFIG_IMPORTER }}
          branch-packager-rules-importer-file: ${{ env.YAML_BRANCH_CONFIG_IMPORTER }}
          consolidated-commit-msg: ${{ env.ALL_DELTA_COMMIT_MSG }}
          artifact-type: docker
          debug: true

      - name: Run Prebuild Script
        if: steps.pipeline-branch-config.outputs.build_prebuild_enabled == 'true'
        run: |
          prebuildScript=${{ steps.pipeline-branch-config.outputs.build_prebuild_script }}
          if [[ -z "$prebuildScript" ]]; then
            echo "[ERROR] Prebuild script is empty. Please fix the controller config before retrying..."
            exit 1
          fi
          if [[ ! -f "$prebuildScript" ]]; then
            echo "[ERROR] Unable to locate prebuild script: $prebuildScript"
            exit 1
          fi

          chmod 755 "$prebuildScript"
          echo "[INFO] Start running prebuild script: $prebuildScript"
          $prebuildScript

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          driver: docker

      - name: Setup jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ENV_1: ${{ secrets.JFROG_ARTIFACTORY_CONFIG }}

      - name: Get Temporary Access Token
        id: arti-access-token
        run: |
          accessUsername=$(jf config show | grep "User:" | awk -F'[\t ]+' '{print $2}' | head -n 1)
          accessToken=$(jf rt access-token-create | jq -r .access_token)
          echo "ARTIFACTORY_TMP_USERNAME=${accessUsername}" >> ${GITHUB_ENV}
          echo "ARTIFACTORY_TMP_TOKEN=${accessToken}" >> ${GITHUB_ENV}
          echo "::add-mask::${accessToken}"
          echo "[INFO] accessUsername: $accessUsername"

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          registry: ${{ env.DOCKER_REGISTRY_BASE_URL }}/${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}
          username: ${{ env.ARTIFACTORY_TMP_USERNAME }}
          password: ${{ env.ARTIFACTORY_TMP_TOKEN }}

      - name: Construct docker artifact base name
        id: artifact-info
        run: |
          artifactGroup=${{ steps.pipeline-branch-config.outputs.artifact_packager_group }}
          FINAL_ARTIFACT_BASE_NAME=${{ env.ARTIFACT_BASE_NAME }}
          if [[ ! -z "$artifactGroup" ]]; then
             FINAL_ARTIFACT_BASE_NAME=$artifactGroup/${{ env.ARTIFACT_BASE_NAME }}
          fi
          echo "FINAL_ARTIFACT_BASE_NAME=${FINAL_ARTIFACT_BASE_NAME}" >> ${GITHUB_ENV}
          echo "name=${FINAL_ARTIFACT_BASE_NAME}" >> $GITHUB_OUTPUT

          tagEnabled=${{ steps.pipeline-branch-config.outputs.artifact_packager_tag_enabled }}
          tagName=${{ steps.pipeline-branch-config.outputs.artifact_packager_tag_name }}
          finalTags=partior.jfrog.io/${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${FINAL_ARTIFACT_BASE_NAME}:${{ steps.version-bot.outputs.artifact-version-name }}
          if [[ "$tagEnabled" == "true" ]] && [[ ! -z "$tagName" ]]; then
            finalTags=$finalTags,partior.jfrog.io/${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${FINAL_ARTIFACT_BASE_NAME}:${tagName}
          fi
          echo "tags=${finalTags}" >> $GITHUB_OUTPUT

      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v3
        with: 
          context: ./
          file: ./${{ steps.pipeline-branch-config.outputs.build_dockerfile }}
          push: ${{ steps.pipeline-branch-config.outputs.artifact_packager_enabled }}
          tags: ${{ steps.artifact-info.outputs.tags }}
          build-args: |
            ART_USER=${{ env.ARTIFACTORY_TMP_USERNAME }}
            ART_TOKEN=${{ env.ARTIFACTORY_TMP_TOKEN }}

      - name: Publish build info
        if: steps.pipeline-branch-config.outputs.artifact_packager_enabled == 'true'
        run: |
          echo "[INFO] Generate temporary manifest..."
          echo "${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${{ env.FINAL_ARTIFACT_BASE_NAME }}:${{ steps.version-bot.outputs.artifact-version-name }}@${{ steps.docker_build.outputs.digest }}" > image_manifest.tmp
          cat image_manifest.tmp

          echo "[INFO] Create build info..."
          echo "jfrog rt bdc ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }} --image-file image_manifest.tmp --build-name \"${GITHUB_WORKFLOW}\" --build-number ${{ github.run_number }}"
          jfrog rt bdc ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }} --image-file image_manifest.tmp --build-name "${GITHUB_WORKFLOW}" --build-number ${{ github.run_number }}

          echo "[INFO] Start publishing build info..."
          echo jfrog rt bp
          jfrog rt bp