name: Update Partior-Stable Version
run-name: Move partior-stable to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true

jobs:
  update-partior-tag:
    uses: partior-libs/controller-3p-pipelines/.github/workflows/pipeline-template-update-partior-stable.yaml@main
    with:
      TARGET-REFERENCE: ${{ github.event.inputs.target }}
    secrets: inherit
